import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";


const myFont = localFont({
  src: '../../public/Noor-Regular.ttf',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={myFont.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <ThemeProvider theme={theme}>
          <NavBar/>
          {children}
          </ThemeProvider>
          </AppRouterCacheProvider>
      </body>
    </html>
  );
}
